/*
    The emoji library (GDD section 3)
    - every collectible emoji carries a club, a colour, a size, and zero or
      more tags - 8 + 12 + 5 + 20 = 45 attributes, a typical emoji carries
      four or five of them
    - the library is encoded, not spelled out: emoji-data.js is the record,
      pack.mjs packs it into the strings below so the shipped copy is small
*/

'use strict';

// the vocabulary, word arrays - order fixes each word's index everywhere
const netClubs = ['sports', 'food', 'nature', 'animals', 'art', 'science', 'games', 'style'];
const netColours = ['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'pink',
    'brown', 'black', 'white', 'grey', 'rainbow'];
const netSizes = ['tiny', 'small', 'medium', 'big', 'huge'];
const netTags =
[
    'plant', 'machine', 'sky', 'drink', 'sea', 'fire', 'cold', 'round',
    'soft', 'scary', 'sharp', 'music', 'night', 'travel',
    'cute', 'smart', 'fancy', 'magic', 'retro', 'party',
];

// the flat 45 word list, and which kind of attribute a word is
const netAttrs = [...netClubs, ...netColours, ...netSizes, ...netTags];
function netAttrKind(word)
{
    return netClubs.includes(word) ? 0 : netColours.includes(word) ? 1 :
        netSizes.includes(word) ? 2 : 3;
}

// Colours near enough to read as a near miss rather than a plain miss (GDD 3),
// as one bit mask per colour in netColours order: bit k set means netColours[k]
// is a neighbour of this one. The seven bright colours are a wheel and the
// wheel wraps, so red sits beside pink; brown sits beside red and orange;
// rainbow sits beside every colour but the greys; and black, white and grey
// are a short line of their own with grey in the middle. The table is
// symmetric, which test/lib.mjs holds it to.
//
// This was twelve arrays of colour names keyed by colour, which read better
// and cost about 400 bytes of the bundle to say exactly the same thing: a
// string survives minification untouched and there were forty of them, all
// spelling words netColours already holds.
const netNear = [2242, 2181, 2058, 2068, 2088, 2128, 2081, 2051, 1024, 1024, 768, 255];

// are these two colours neighbours? either way round - the table is symmetric
function netIsNear(a, b)
{
    return netNear[netColours.indexOf(a)] >> netColours.indexOf(b) & 1;
}

// Date locations (GDD section 10): glyph -> [name, [attribute words], season,
// the place it stands in for]. Season is 0-3, undefined for always available,
// -1 for one week only. Keys are quoted because they are looked up only by a
// string glyph out of dateLocations: Closure ADVANCED renames an unquoted
// literal key and leaves the bracket lookup alone - the one table in the game
// that still needs it. The two one-week places share their week with the
// matching calEvents row in calendar.js: 🎆 is the week-16 summer festival,
// ⛩️ the week-33 New Year.
//
// The fourth field is what makes the weekend six tiles every week of the year
// (dateLocations): a season does not add a place, it takes one's tile. The
// beach is summer's park and the mountain is winter's tower - the same
// outdoors and the same big view - the festival is the week the mall is
// empty, and New Year is at the shrine instead of the museum. Six permanent
// places and four stand-ins, never seven and never eight.
const netPlaces =
{
    '🏖️': ['the beach', ['sea', 'blue'], 1, '🌳'],
    '🏔️': ['the mountain', ['cold', 'huge'], 3, '🗼'],
    '🌳': ['the park', ['plant', 'green']],
    '🏛️': ['the museum', ['art', 'big']],
    '🕹️': ['the arcade', ['games', 'machine']],
    '🏟️': ['the stadium', ['sports', 'round']],
    '🛍️': ['the mall', ['style', 'pink']],
    '🗼': ['the tower', ['travel', 'huge', 'night']],
    '🎆': ['the festival', ['fire', 'night'], -1, '🛍️'],
    '⛩️': ['the shrine', ['travel', 'night'], -1, '🏛️'],
};

//<pack> regenerated by: npm run pack - do not hand edit
const NET_EMOJI = '🐧🦇🦄🐝🐛🐞🕷️🐢🦖🦑🦐🦀🐡🐠🐳🦈🐘🦘🐎🐐🦢🦩🐇🐿️🌵🌳🍀🍂🍁💐🌸🌑🌕🌎🪐⚡☄️💥🔥🌪️🌈☀️☁️❄️⛄🌊🌌🍥🫐🍐🍊🍌🍉🍇🍓🌶️🍞🧀🍩🥛☕🍵🧃🥤🧊🏀🏈🎾🏐🎱⛳🎣🥊🛹⛸️🎿🏄🏆🎨🖌️🖍️🎭🎬🎧🎹🥁🎸🎻📷✏️📌📎📚📖🔬🔭💡🧪⚙️🧯👾🎮🕹️🎲♟️🎯🎳🃏🧩🎰🧸🩰🧶👑💎👚🧥🧣🧤👜👢👒🎩🧢🎀💼💀🎃🧙🔮🕯️🌋🚂🚀🛸🚁⛵🏎️🍷🧁🎵🎙️🔑🔊🧠🎊🎆🕶️☂️🎒🍧🍹';
const NET_PACK  = 'EC41GESXO0EuYG0Bu0G4Cq000BG424Dm080CG00GCS0O0DK08GBG00GBK0GGDW0GGBy00GCm00GEa0OGEa200Bm040De240EC040ECG0KDGG04ES440DW4408a0G18e0018S0019m0017a001B40019O401M812484124KG124JK124JK1eWKG10aJC00WJC00WAu084BCW048402aAa0448m014AS0508y01OKaX045i020500214m021480214S0015m0215KG213m4013m00X640404SGG0604606e028608284q0284O00854028560180O0202G020100202u0202a020140011O0GG08000082002y2101O2H01O20G0mG00Ia020GK040F4020IaJW0G4002GO0W2Hy0W2FA0Y0FA0W2HLQW0Hb202Fi8G0F00G0I8802Ia800Hy800Lu802J0906J8802Jm800Ly002Iu00YO5080P4002Mb002MX000P0800Mg020P8020OAW00NS800PT002Om540SCK40Ra060R0G00RWGH0Ry040Re050QO050TW050Ry300Sa000Qi420R$n20Re040QK440Sa200LiWA0FS1AWMyW00OCX20J9X0W8428aIz202KG30cM4B06Ja206JG20G0W2003qQ087G460GO0W0IC0W2Ky0G2Le0W2Km840Q6000N$10aSv004RyI04QO2005i4504A208';
//</pack>

///////////////////////////////////////////////////////////////////////////////
// Seeded random, so a seed reproduces a run's opinions exactly (GDD 3)
// Lehmer generator, small and good enough for rolling favorites

let netSeed = 1;

function netSetSeed(seed) { netSeed = seed%2147483647 || 1; }

function netRandInt(max)
{
    netSeed = netSeed*16807 % 2147483647;
    return netSeed % max;
}

// pick one item from an array
function netPick(list) { return list[netRandInt(list.length)]; }

///////////////////////////////////////////////////////////////////////////////

// split a string into emoji, keeping variation selectors attached to their
// glyph - iterating a string gives them as separate code points
function netSplit(text)
{
    const list = [];
    for (const c of text)
        if (c == '️' && list.length) // variation selector, invisible on its own
            list[list.length-1] += c;
        else
            list.push(c);
    return list;
}

///////////////////////////////////////////////////////////////////////////////

// one integer per emoji, mixed radix then 20 tag bits, five base-64 characters
// big-endian - see pack.mjs, which builds NET_EMOJI and NET_PACK from this
const NET_ALPHA = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz$_';
let netLib = [], netByEmoji = {};

// one club's emoji, in library order - the shelf School, the keyboard, the
// exam's forced club and the starting hand all read
function netClub(club) { return netLib.filter(r => r.club == club); }

// decode NET_EMOJI/NET_PACK into netLib/netByEmoji, call once at startup
function netInit()
{
    netLib = netSplit(NET_EMOJI).map((e, i) =>
    {
        // five characters, 30 bits: a 20-bit tag mask under club, colour and
        // size (tools/pack.mjs is the other half of this layout)
        let n = 0;
        for (let j = 0; j < 5; ++j)
            n = n*64 + NET_ALPHA.indexOf(NET_PACK[i*5 + j]);
        const bits = n & 1048575; n >>= 20;
        const size = n%5; n = n/5 | 0;
        const colour = n%12, club = n/12 | 0;
        const tags = netTags.filter((t, k) => bits & 1 << k);
        return netByEmoji[e] = {e, club: netClubs[club],
            colour: netColours[colour], size: netSizes[size], tags};
    });
}
