/*
    The emoji library (GDD section 3)
        - every collectible emoji carries a club, a colour, and zero or more tags
            - 8 + 12 + 22 = 42 attributes, a typical emoji carries four or five
      four or five of them
    - the library is encoded, not spelled out: emoji-data.js is the record,
      pack.mjs packs it into the strings below so the shipped copy is small
*/

'use strict';

// the vocabulary, word arrays - order fixes each word's index everywhere
const netClubs = ['sports', 'food', 'nature', 'animals', 'art', 'science', 'games', 'style'];
const netColours = ['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'pink',
    'brown', 'black', 'white', 'grey', 'rainbow'];
const netTags =
[
    'plant', 'machine', 'sky', 'drink', 'sea', 'fire', 'cold', 'round',
    'soft', 'scary', 'sharp', 'music', 'night', 'travel',
    'cute', 'fancy', 'magic', 'party', 'tiny', 'huge', 'rideable',
];

// the flat 41 word list, and which kind of attribute a word is
const netAttrs = [...netClubs, ...netColours, ...netTags];
function netAttrKind(word)
{
    return netClubs.includes(word) ? 0 : netColours.includes(word) ? 1 : 3;
}

// Colours near enough to read as a near miss rather than a plain miss (GDD 3),
// as one bit mask per colour in netColours order: bit k set means netColours[k]
// is a neighbour of this one. The seven bright colours are a wheel and the
// wheel wraps, so red sits beside pink; brown sits beside red and orange;
// rainbow sits beside every colour but the greys; and black, white and grey
// are a short line of their own with grey in the middle. The table is
// symmetric, which test/lib.mjs holds it to.
//
// This was twelve arrays of colour names keyed by colour, which read better
// and cost about 400 bytes of the bundle to say exactly the same thing: a
// string survives minification untouched and there were forty of them, all
// spelling words netColours already holds.
const netNear = [2242, 2181, 2058, 2068, 2088, 2128, 2081, 2051, 1024, 1024, 768, 255];

// are these two colours neighbours? either way round - the table is symmetric
function netIsNear(a, b)
{
    return netNear[netColours.indexOf(a)] >> netColours.indexOf(b) & 1;
}

// Date locations (GDD section 10): glyph -> [name, [attribute words], season,
// the place it stands in for]. Season is 0-3, undefined for always available,
// -1 for one week only. Keys are quoted because they are looked up only by a
// string glyph out of dateLocations: Closure ADVANCED renames an unquoted
// literal key and leaves the bracket lookup alone - the one table in the game
// that still needs it. The two one-week places share their week with the
// matching calEvents row in calendar.js: 🎆 is the week-16 summer festival,
// ⛩️ the week-33 New Year.
//
// The fourth field is what makes the weekend six tiles every week of the year
// (dateLocations): a season does not add a place, it takes one's tile. The
// beach is summer's park and the mountain is winter's tower - the same
// outdoors and the same big view - the festival is the week the mall is
// empty, and New Year is at the shrine instead of the museum. Six permanent
// places and four stand-ins, never seven and never eight.
const netPlaces =
{
    '🏖️': ['the beach', ['sea', 'blue'], 1, '🌳'],
    '🏔️': ['the mountain', ['cold', 'huge','sky'], 3, '🗼'],
    '🌳': ['the park', ['plant', 'green']],
    '🏛️': ['the museum', ['art', 'tiny']],
    '🕹️': ['the arcade', ['games', 'machine']],
    '🏟️': ['the stadium', ['sports', 'round']],
    '🛍️': ['the mall', ['style', 'pink']],
    '🗼': ['the tower', ['travel', 'huge']],
    '🎆': ['the festival', ['fire', 'night'], -1, '🛍️'],
    '⛩️': ['the shrine', ['travel', 'night'], -1, '🏛️'],
};

//<pack> regenerated by: npm run pack - do not hand edit
const NET_EMOJI = '🐧🦇🦄🐝🦋🐞🕷️🐢🦖🦑🦀🐠🐳🦈🐘🐎🐐🦢🦩🐇🌵🌳🍀🍂🍁💐🌸🌑🌕🪐⚡☄️💥🔥🌪️🌈☀️☁️❄️⛄🌊🌌🍥🫐🍐🍊🍌🍇🍓🌶️🍞🧀🍩🥛☕🍵🧃🥤🧊🏀🏈⚾🎾🎱⛳🎣🛹⛸️🎿🏄🏆🎨🖌️🖍️🎭🎬🎤🎧🎹🥁🎷🎸🎻📷🖼️✏️📌📎📚🔬🔭💾🧮💡🧪⚙️👾🕹️🎲♟️🎯🃏🧩🎰🧸🩰🧶👑💎👚🧥🧣🧤👜👒🎩🧢🎀💼💀👻🎃🧙🔮🗿🕯️🌋🚂🚀🛸✈️🚁⛵🏎️🌍🍷🧁🔑🧭🔊🎊🎆☂️🎒🍧🍹💩💪🦠';
const NET_PACK  = '5e41G5mHO05yKG04n4G4514044X4245X0804u40G4w0O05G08G4W0GG4m40G5200G5m0OG5s0005S0405e4405e80K5G8045mK403O0G13O0013P0013v001310014O4013n4018o1243A1247g1247g18W82H0a7e08W7e00W4I0844QK043A02a4A0443X014480503Y21O8AH042H420210211u0011e0211m001290211X0011X00X2O0401m8G02O4602e0082O0081u0081m40820W0820W18080200u000180200O060100200O8010W0GG040021C0H00a0100a00G0G8007O0206W040614007OBW06O0027GWW26W0W2780W260WY0680W060WW26uAW0702027OA006G0G0610G07H0007O0008n0027Y1068W0028u0027e1027uG088m0029e4809000291000A100090W209em009P000A82029u440BGC40B0060Am800B18H0B8040B0050AW250Bm850B8B00Ae400B8P00B0040AW440BO2008eH80A8180681AW98m009eG207A2007eH0W3A28W7a2028610c8q106842067q2067i20I0C2023Y2241WA082v4408O0G27e2208e0W2AOW009WX0aB8204AW2002G4501eW083u4400G0007v081';
//</pack>

///////////////////////////////////////////////////////////////////////////////
// Seeded random, so a seed reproduces a run's opinions exactly (GDD 3)
// Lehmer generator, small and good enough for rolling favorites

let netSeed = 1;

function netSetSeed(seed) { netSeed = seed%2147483647 || 1; }

function netRandInt(max)
{
    netSeed = netSeed*16807 % 2147483647;
    return netSeed % max;
}

// pick one item from an array
function netPick(list) { return list[netRandInt(list.length)]; }

///////////////////////////////////////////////////////////////////////////////

// split a string into emoji, keeping variation selectors attached to their
// glyph - iterating a string gives them as separate code points
function netSplit(text)
{
    const list = [];
    for (const c of text)
        if (c == '️' && list.length) // variation selector, invisible on its own
            list[list.length-1] += c;
        else
            list.push(c);
    return list;
}

///////////////////////////////////////////////////////////////////////////////

// one integer per emoji, mixed radix then 21 tag bits, five base-64 characters
// big-endian - see pack.mjs, which builds NET_EMOJI and NET_PACK from this
const NET_ALPHA = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz$_';
let netLib = [], netByEmoji = {};

// one club's emoji, in library order - the shelf School, the keyboard, the
// exam's forced club and the starting hand all read
function netClub(club) { return netLib.filter(r => r.club == club); }

// decode NET_EMOJI/NET_PACK into netLib/netByEmoji, call once at startup
function netInit()
{
    netLib = netSplit(NET_EMOJI).map((e, i) =>
    {
        // five characters, 28 bits: a 21-bit tag mask under club and colour
        // (tools/pack.mjs is the other half of this layout)
        let n = 0;
        for (let j = 0; j < 5; ++j)
            n = n*64 + NET_ALPHA.indexOf(NET_PACK[i*5 + j]);
        const bits = n & 2097151; n >>= 21;
        const colour = n%12, club = n/12 | 0;
        const tags = netTags.filter((t, k) => bits & 1 << k);
        return netByEmoji[e] = {e, club: netClubs[club],
            colour: netColours[colour], tags};
    });
}
